### ISSUE TITLE
bake test:external failure

### ISSUE THREAD

**Issue by loqs** [ioquatix/bake-test-external#3]
Gems used
bake v0.18.2
bake v0.2.0
bake-test-external v0.3.2

Commands used
```
bake test:external
Cloning into 'external/bake'...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using fiber-annotation 0.2.0
Using fiber-local 1.0.0
Using bundler 2.4.13
Using sus 0.21.1
Using mapping 1.1.1
Fetching msgpack 1.7.1
Using console 1.17.2
Fetching samovar 2.2.0
Installing samovar 2.2.0
Using bake 0.18.2 from source at `.` and installing its executables
Using bake-test-external 0.3.2 from source at `../..`
Using bake-test 0.2.0
Installing msgpack 1.7.1 with native extensions
Fetching covered 0.22.0
Installing covered 0.22.0
Bundle complete! 10 Gemfile dependencies, 12 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
4 installed gems you directly depend on are looking for funding.
  Run `bundle fund` for details
bundler: failed to load command: rspec (/usr/bin/rspec)
/usr/lib/ruby/3.0.0/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable rspec for gem rspec-core. rspec-core is not currently included in the bundle, perhaps you meant to add it to your gems.rb? (Gem::Exception)
	from /usr/lib/ruby/3.0.0/bundler/rubygems_integration.rb:336:in `block in replace_bin_path'
	from /usr/bin/rspec:25:in `<top (required)>'
	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /usr/lib/ruby/3.0.0/bundler/cli.rb:492:in `exec'
	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/lib/ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/lib/ruby/3.0.0/bundler/cli.rb:28:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
	from /usr/lib/ruby/3.0.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
	from /usr/bin/bundle:25:in `load'
	from /usr/bin/bundle:25:in `<main>'
External tests bake failed!
```
Could this be related to ioquatix/bake@c6b0d313a216077ceff460e2e90324206f3c243f which switched from rspec to sus?
While https://github.com/ioquatix/bake-test-external/blob/0f5b0ba012d6a700ba6b6e60a14b1df90a5223f2/config/external.yaml#L3 still uses rspec.

**Comment by ioquatix** [comment]
Thanks for your report, this should be fixed now.
